/* V3.1 Senior Manager Mode: explainable local-first recommendations; no API. */
(()=>{
const e=x=>esc(String(x??''));
const goals={awareness:'Show your services to new relevant people. Test discovery posts and locally relevant short videos.',engagement:'Invite useful questions and conversations. Prefer saves, shares and meaningful replies over empty engagement.',leads:'Answer customer objections and make the enquiry process easy. Track qualified enquiries, not only likes.',sales:'Explain the offer, the booking process and why it is suitable. Never invent discounts or availability.',trust:'Show verifiable processes, team details and permission-cleared testimonials. Avoid unsupported claims.'};
const playbooks=[{terms:/tour|travel|beach|adventure|water sport|hotel|resort/i,heading:'Tourism & experiences',ideas:['Show the visitor journey using permission-cleared footage','Explain what customers should know before booking','Answer common safety and logistics questions'],checks:['Confirm activity availability, safety requirements and current prices','Only use genuine, permission-cleared media']},{terms:/restaurant|cafe|food|bakery|kitchen/i,heading:'Food & hospitality',ideas:['Show a genuine popular item and what makes it special','Explain ordering and delivery details','Highlight authentic customer feedback with permission'],checks:['Confirm menu prices and current availability','Avoid unsupported health or ingredient claims']},{terms:/beauty|salon|spa|clinic/i,heading:'Beauty & wellness',ideas:['Explain a service and who it is appropriate for','Introduce the team and their credentials','Answer frequently asked questions'],checks:['Avoid guaranteed results or misleading before-and-after claims','Use consented customer photos only']},{terms:/real estate|property|builder/i,heading:'Property & real estate',ideas:['Explain a buyer checklist','Show verified amenities and neighbourhood information','Clarify enquiry and site-visit process'],checks:['Verify legal claims, prices and property availability','Do not promise returns']}];
function playbook(c){return playbooks.find(p=>p.terms.test([c.industry,c.services,c.name].join(' ')))||{heading:'Small business',ideas:['Explain one customer problem you solve','Show how your service works','Answer the most common buying question'],checks:['Verify prices, offers and service details','Use approved visuals and truthful claims']}}
function tasks(){let now=today(),end=new Date();end.setDate(end.getDate()+3);let horizon=end.toISOString().slice(0,10);let rows=[];for(const c of state.clients.filter(c=>c.status==='active')){let strategy=state.strategies?.[c.id],sub=subFor(c.id),items=state.content.filter(x=>x.clientId===c.id&&x.date.startsWith(month()));if(!strategy)rows.push({priority:1,c,text:'Complete strategic onboarding',detail:'Understand goals and customer objections before planning.',action:'strategy'});else if(!sub)rows.push({priority:1,c,text:'Assign a monthly package',detail:'Set clear deliverable quantities before creating the calendar.',action:'subscription'});else if(!items.length)rows.push({priority:2,c,text:'Prepare this month’s content plan',detail:'Create a goal-led draft and review ideas.',action:'plan'});
for(const x of items){if(x.status==='published'||x.status==='cancelled')continue;if(x.date<now)rows.push({priority:0,c,text:'Overdue: '+x.title,detail:'Planned '+x.date+' · '+x.type+' · '+x.status,action:'content',item:x});else if(x.date<=horizon)rows.push({priority:2,c,text:'Upcoming: '+x.title,detail:x.date+' · '+x.type+' · '+x.status,action:'content',item:x});if(x.status==='awaiting-approval')rows.push({priority:1,c,text:'Follow up on approval: '+x.title,detail:'Ask the client to approve or request changes.',action:'content',item:x});}
}return rows.sort((a,b)=>a.priority-b.priority).slice(0,18)}
function guidance(c){const s=state.strategies?.[c.id],p=playbook(c),goal=s?.goal||'leads',items=state.content.filter(x=>x.clientId===c.id&&x.date.startsWith(month())),published=items.filter(x=>x.status==='published');let missing=[];if(!c.audience?.trim())missing.push('target audience');if(!c.services?.trim())missing.push('services');if(!s)missing.push('strategic goals');if(!state.brandProfiles?.[c.id])missing.push('brand profile');let checks=[...p.checks,'Check the caption, hook and clear call to action','Confirm that all claims are supported and client approval is recorded','Check that the content uses the approved brand guidelines'];return `<section class="panel manager-panel"><div class="row between"><div><div class="eyebrow">SENIOR MANAGER MODE · RULE-BASED</div><h2>Strategy guidance</h2></div><span class="pill">${e(p.heading)}</span></div><p><b>Why this direction:</b> ${e(goals[goal]||goals.leads)}</p>${missing.length?`<p class="manager-warning">Complete these details to improve recommendations: ${e(missing.join(', '))}.</p>`:''}<h3>Ideas to develop this month</h3><div class="manager-tips">${p.ideas.map(t=>`<div>• ${e(t)}</div>`).join('')}</div><h3>Pre-publish quality checklist</h3><div class="manager-checks">${checks.map((t,i)=>`<label><input type="checkbox" data-qc="${i}" data-clientid="${e(c.id)}"> ${e(t)}</label>`).join('')}</div><p class="hint">Checklist ticks are a temporary review aid, not proof of client approval. Save actual approval status in the content record.</p><h3>Performance coaching</h3><p>${published.length<3?'Insufficient published content this month for a meaningful pattern. Publish consistently, then enter real reach, saves, shares and enquiry data.':`You have ${published.length} published items this month. Compare results for similar formats and topics before changing the strategy. Avoid drawing conclusions from one viral post.`}</p><div class="actions"><button class="btn primary" data-manager="strategy" data-id="${e(c.id)}">${s?'Review growth blueprint':'Complete strategic onboarding'}</button><button class="btn" data-manager="plan" data-id="${e(c.id)}">Review monthly plan</button></div></section>`}
function command(){let rows=tasks();return `<section class="panel manager-panel"><div class="row between"><div><div class="eyebrow">AGENCY COMMAND CENTER</div><h2>Your next priority actions</h2></div><span class="muted small">${rows.length} actionable items</span></div><p class="muted small">Recommendations are calculated from your saved client data and content deadlines. No background notifications or Instagram connection.</p>${rows.length?rows.map(r=>`<div class="manager-task"><div><strong>${e(r.text)}</strong><div class="muted small">${e(r.c.name)} · ${e(r.detail)}</div></div><button class="btn small" data-manager="${r.action}" data-id="${e(r.c.id)}" ${r.item?`data-item="${e(r.item.id)}"`:''}>Open →</button></div>`).join(''):'<div class="empty">No outstanding actions. Add a client or continue with your monthly workflow.</div>'}</section>`}
function mount(){let root=document.querySelector('#view');if(!root)return;if(page==='overview'){root.insertAdjacentHTML('afterbegin',command());}if(page==='workspace'){let c=workClient();if(c)root.insertAdjacentHTML('beforeend',guidance(c));}}
const prior=render;render=function(...args){prior(...args);mount()};
document.addEventListener('click',ev=>{const el=ev.target.closest('[data-manager]');if(!el)return;ev.preventDefault();const id=el.dataset.id;switch(el.dataset.manager){case 'strategy':if(typeof strategyPanel==='function')strategyPanel(id);else document.querySelector(`[data-v3="panel"][data-id="${id}"]`)?.click();break;case 'plan':openWorkspace(id);document.querySelector(`[data-v3="preview"][data-id="${id}"]`)?.click()||document.querySelector(`[data-v3="panel"][data-id="${id}"]`)?.click();break;case 'subscription':action('subscription',id);break;case 'content':openWorkspace(id);if(el.dataset.item)action('editContent',el.dataset.item);break;}});
// Older installations may still contain the original sample. Only offer an explicit cleanup.
function isDemo(c){return c.name==='Sample Umrah Tours & Travels'&&String(c.notes||'').includes('SAMPLE CLIENT')}
function demoNotice(){if(!state?.clients?.some(isDemo))return;let root=document.querySelector('#view');if(!root||page!=='clients')return;root.insertAdjacentHTML('afterbegin',`<section class="panel manager-panel"><h2>Old demonstration client detected</h2><p>Earlier versions included Sample Umrah Tours & Travels. You can remove this sample and its linked sample records without affecting your real clients.</p><button class="btn" data-manager="remove-demo">Remove demo client and sample records</button></section>`)}
const rendered=render;render=function(...args){rendered(...args);demoNotice()};
document.addEventListener('click',async ev=>{if(!ev.target.closest('[data-manager="remove-demo"]'))return;const samples=state.clients.filter(isDemo);if(!samples.length)return;if(!confirm('Remove the original sample Umrah client and ALL its linked data? Export a backup first. This cannot be undone.'))return;const ids=new Set(samples.map(x=>x.id));state.clients=state.clients.filter(x=>!ids.has(x.id));for(const key of ['subscriptions','invoices','content','insights','audienceSlots'])if(Array.isArray(state[key]))state[key]=state[key].filter(x=>!ids.has(x.clientId));const invoiceIds=new Set((state.invoices||[]).map(x=>x.id));state.payments=(state.payments||[]).filter(x=>invoiceIds.has(x.invoiceId));for(const key of ['strategies','brandProfiles','audienceProfiles'])for(const id of ids)if(state[key])delete state[key][id];filters.workspaceClient='';await commit('Demo client removed. Other clients preserved.');});
})();
