// Social Desk V3.2 — optional production methods and separate caption workspace.
function productionStudio(id){
 const x=state.content.find(z=>z.id===id);if(!x)return;
 const c=client(x.clientId),b=brandFor(x.clientId),saved=x.productionMethod||'manual';
 modal('Content Production Studio · '+x.title,`<p class="hint">Choose how to produce this ${esc(x.type.toLowerCase())}. AI visuals are optional. Caption creation is a separate step.</p><div class="formgrid"><label class="full">Production method<select id="studioMethod"><option value="manual" ${saved==='manual'?'selected':''}>Manual design / Canva</option><option value="real" ${saved==='real'?'selected':''}>Real photos or video</option><option value="ai" ${saved==='ai'?'selected':''}>AI image / visual prompt</option></select></label></div><div class="actions" style="margin:12px 0"><button class="btn primary" id="studioSave">Save choice</button><button class="btn" id="studioCaption">Caption Studio</button></div><p class="hint" id="studioNotice"></p><textarea id="studioBrief" readonly style="width:100%;min-height:290px"></textarea><div class="actions"><button class="btn primary" id="studioCopy">Copy production brief</button><button class="btn" id="studioEdit">Edit content / attach link</button></div>`);
 const method=$('#studioMethod'),area=$('#studioBrief');
 const update=()=>{let m=method.value;area.value=makeProductionBrief(x,c,b,m);$('#studioNotice').textContent=m==='ai'?'AI-generated imagery is optional. Do not fabricate client locations, customers, safety procedures or service details.':m==='real'?'Use permission-cleared genuine media. Do not encourage unsafe filming.':'This is a practical brief for Canva or another editing app; no AI image required.'};
 method.onchange=update;update();
 $('#studioSave').onclick=async()=>{x.productionMethod=method.value;x.updatedAt=new Date().toISOString();await commit('Production method saved');toast('Production choice saved')};
 $('#studioCaption').onclick=()=>captionStudio(id);$('#studioCopy').onclick=()=>copy(area.value);$('#studioEdit').onclick=()=>contentForm(id);
}
function makeProductionBrief(x,c,b,m){
 const reel=x.type==='Reel',story=x.type==='Story';let fmt=reel||story?'9:16 vertical':'4:5 portrait (or approved brand format)';
 let intro=`CLIENT: ${c?.name||''}\nINDUSTRY: ${c?.industry||''}\nTOPIC: ${x.title}\nFORMAT: ${x.type} — ${fmt}\nOBJECTIVE: ${x.objective||'Align with client growth strategy'}\nAUDIENCE: ${c?.audience||'Confirm target audience'}\nVERIFIED SERVICES: ${c?.services||'Not supplied'}\nBRAND COLORS: ${b.primary}, ${b.secondary}, ${b.accent}\nTYPOGRAPHY: ${b.typography}\nVISUAL STYLE: ${b.visualStyle}\nLOGO RULES: ${b.logoInstructions}\nDESIGN NOTES: ${x.designNotes||'None'}\nASSETS: ${x.assetNotes||'Request approved assets'}\nCTA: ${x.cta||'Use approved booking/enquiry CTA'}\n\n`;
 if(m==='manual')return intro+(reel?'MANUAL REEL EDITING PLAN: Develop a strong first 2-second hook, 4–6-shot storyboard, on-screen text, B-roll requirements, transition guidance, subtitle style, music rights check, and end-screen CTA. Specify what footage the client must provide.':story?'MANUAL STORY DESIGN: Prepare a 9:16 Canva layout with clear headline, one key message, unobstructed visual, small branding, safe text margins and optional native Instagram poll/slider/question sticker.':'MANUAL CANVA DESIGN: Provide exact layout hierarchy, headline and supporting copy, image placement, suggested typography sizes, spacing, contrast, icon/photo choices and a clear CTA. If carousel, specify slide-by-slide layout. Keep everything editable.')+'\n\nDo not invent business claims, prices or testimonials. Review before publishing.';
 if(m==='real')return intro+(reel?'REAL-FOOTAGE REEL: Request permission-cleared client footage; provide a shot list, hook, sequence, subtitles, editing rhythm, cover frame and end CTA. Never instruct filming while operating vehicles or equipment.':story?'REAL-MEDIA STORY: Choose a genuine approved vertical photo or clip; suggest crop, headline, minimal brand overlay and interactive sticker.':'REAL-PHOTO POST: Select a genuine approved client photo, recommend crop and color correction, readable overlay and CTA. No synthetic customer imagery.')+'\n\nCheck media permissions, factual accuracy and safe depiction.';
 return intro+(reel?'OPTIONAL AI VISUAL PROMPT: Suggest AI-generated supporting frames or a cover concept only, with storyboard and editable overlays. Do not imply synthetic footage is a real customer experience.':'OPTIONAL AI IMAGE PROMPT: Create a visually polished concept consistent with the saved brand. Keep important text editable in Canva. Do not invent the actual venue, staff, customers, services, prices, testimonials or logos.')+'\n\nUse verified real client assets where authenticity matters. Clearly review synthetic imagery for misleading details.';
}
function captionStudio(id){
 const x=state.content.find(z=>z.id===id);if(!x)return;let c=client(x.clientId),b=brandFor(x.clientId);
 let seed=x.caption||`${x.title}\n\n${x.type==='Reel'?'See the experience in action.':x.type==='Story'?'Discover more about this experience.':'Discover what makes this worth exploring.'}\n\n${x.cta||'Message us for details.'}`;
 modal('Caption Studio · '+x.title,`<p class="hint">Write or refine a caption here, independently of whether you use Canva, real media, or AI visuals. The draft is a template, not AI-generated.</p><label>Caption (editable)<textarea id="studioCaptionText" style="width:100%;min-height:210px">${esc(seed)}</textarea></label><div class="actions" style="margin:12px 0"><button class="btn primary" id="studioCaptionSave">Save caption</button><button class="btn" id="studioCaptionCopy">Copy caption</button><button class="btn" id="studioCaptionPrompt">Generate ChatGPT caption prompt</button></div><div id="studioCaptionExtra"></div>`);
 $('#studioCaptionSave').onclick=async()=>{x.caption=$('#studioCaptionText').value.trim();x.updatedAt=new Date().toISOString();await commit('Caption saved');toast('Caption saved')};
 $('#studioCaptionCopy').onclick=()=>copy($('#studioCaptionText').value);
 $('#studioCaptionPrompt').onclick=()=>{let prompt=`Act as a senior Instagram copywriter. Write 3 distinct, natural captions for a ${x.type} titled "${x.title}" for ${c?.name||'the client'}. Business: ${c?.industry||''}. Verified services: ${c?.services||''}. Audience: ${c?.audience||''}. Brand voice: ${b.tone||''}. Objective: ${x.objective||'support the client goal'}. CTA: ${x.cta||'encourage relevant enquiries'}. Existing draft: ${$('#studioCaptionText').value}. Include a strong opening, useful information, a relevant CTA, and 5–8 carefully chosen hashtags. Do not invent offers, prices, reviews, locations or guarantees. Identify any missing facts that require client confirmation. Return caption text, hashtags, and a short rationale. Do NOT generate an image.`;$('#studioCaptionExtra').innerHTML=`<p class="hint">Copy this prompt into ChatGPT. Paste the resulting caption into the editable field above and save it.</p><textarea id="studioGeneratedPrompt" readonly style="width:100%;min-height:230px">${esc(prompt)}</textarea><button class="btn primary" id="studioPromptCopy">Copy ChatGPT prompt</button>`;$('#studioPromptCopy').onclick=()=>copy(prompt)};
}
